apiVersion: apps/v1
kind: Deployment
metadata:
  name: contatos-db
  labels:
    app: contatos-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contatos-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: contatos-db
    spec:
      containers:
      - name: contatos-db
        image: mysql:5.7
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: contatos-persistent-storage
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: contatos-db-secret
                key: password
      volumes:
      - name: contatos-persistent-storage
        persistentVolumeClaim:
          claimName: contatos-pv-claim