#!/bin/bash

################################################
# Removendo a configuração do Ingress
################################################

kubectl delete -f ingress.yaml

################################################
# Removendo a configuração do service
################################################

kubectl delete -f deployment.yaml; kubectl delete -f service.yaml;

kubectl delete -f pvc.yaml; kubectl delete pv pv-volume