#!/bin/bash

################################################
# Removendo a configuração do Ingress
################################################

kubectl delete -f ingress.yaml

################################################
# Removendo a configuração do frontend
################################################

kubectl delete -f service.yaml