apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.frontend.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.global.frontend.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.global.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.global.frontend.name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Values.global.frontend.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.global.backend.name }}-configmap
                  key: url
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
