apiVersion: v1
kind: Service
metadata:
  name: todolist-db
  labels:
    run: todolist-db
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: todolist-db
