#!/bin/bash

build_backend_image() {
    
    ################################################
    # Gerando a imagem docker do backend
    ################################################
    
    cd backend
    
    docker build . -t devopsufscar/contatos-v3-backend
    
    cd ..
}

build_frontend_image() {
    
    ################################################
    # Gerando a imagem docker do frontend
    ################################################
    
    cd frontend
    
    docker build . -t devopsufscar/contatos-v3-frontend
    
    cd ..
}

################################################
# Verificando flag -bf
################################################

while getopts ":bf" option; do
   case $option in
      b) # imagem backend
         build_backend_image
         ;;
      f) # imagem frontend
         build_frontend_image
         ;;
   esac
done

################################################
# Executando o docker compose (UP)
################################################

docker compose up
