#!/bin/bash

load_image() {
    
    echo "$(echo "Loading")" "$(echo $1)"

    minikube image load $1

    echo "$(echo "Loaded")" "$(echo $1)"
}

build_backend_image() {
    
    ################################################
    # Gerando a imagem docker do backend
    ################################################
    
    cd backend
    
    # eval ${minikube docker-env}

    docker build . -t devopsufscar/contatos-v3-backend

    load_image devopsufscar/contatos-v3-backend

    cd ..
}

build_frontend_image() {
    
    ################################################
    # Gerando a imagem docker do frontend
    ################################################
    
    cd frontend
    
    # eval ${minikube docker-env}
    
    docker build . -t devopsufscar/contatos-v3-frontend
    
    load_image devopsufscar/contatos-v3-frontend

    cd ..
}

init_minikube() {

    ################################################
    # Inicializando o Minikube
    ################################################

    minikube start

    ################################################
    # Habilitando o Ingress
    ################################################

    minikube image load k8s.gcr.io/ingress-nginx/controller:v1.9.4

    minikube addons enable ingress

    ################################################
    # Inicializando o DashBoard
    ################################################

    minikube addons enable dashboard

    minikube addons enable metrics-server

    minikube dashboard &
}

################################################
# Verificando flag -ibf
################################################

while getopts ":ibf" option; do
   case $option in
      i) # init minikube
         init_minikube
         load_image mysql:5.7
         ;;
      b) # build backend image
         build_backend_image
         ;;
      f) # build frontend image
         build_frontend_image
         ;;
   esac
done

################################################
# Instalando via helm
################################################

helm install contatos contatos-chart
