kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.db.name }}-configmap
data:
  database_url: jdbc:mysql://{{ .Release.Name }}-{{ .Values.global.db.name }}:3306/{{ .Release.Name | title }}?createDatabaseIfNotExist=true