apiVersion: apps/v1
kind: Deployment
metadata:
  name: cidades-frontend
  labels:
    app: cidades-frontend
spec:
  selector:
    matchLabels:
      app: cidades-frontend
  template:
    metadata:
      labels:
        app: cidades-frontend
    spec:
      containers:
        - name: frontend
          image: devopsufscar/cidades-v1-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: cidades-backend-configmap
                  key: url
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"