apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.db.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.global.db.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.global.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.global.db.name }}
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Values.global.db.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-{{ .Values.global.db.name }}-secret
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-{{ .Values.global.db.name }}-secret
                key: password
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        volumeMounts:
          - name: {{ .Release.Name }}-{{ .Values.global.db.name }}-persistent-storage
            mountPath: /data/db
      volumes:
        - name: {{ .Release.Name }}-{{ .Values.global.db.name }}-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Values.global.db.name }}-pv-claim
