apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  labels:
    run: {{ .Release.Name }}-db
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-db
