#!/bin/bash

build_publisher_image() {
    
    ################################################
    # Gerando a imagem docker do publisher
    ################################################
    
    cd Publisher
    
    mvn package clean
        
    cd ..
}

build_subscriber_image() {
    
    ################################################
    # Gerando a imagem docker do subscriber
    ################################################
    
    cd Subscriber
    
    mvn package clean
    
    cd ..
}

################################################
# Verificando flag -ps
################################################

while getopts ":ps" option; do
   case $option in
      p) # imagem ps-publisher
         build_publisher_image
         ;;
      s) # imagem ps-subscriber
         build_subscriber_image
         ;;
   esac
done

################################################
# Executando o docker compose
################################################

docker compose up