services:
  publisher:
    image: devopsufscar/ps-publisher
    restart: always
    container_name: publisher
    env_file:
      - .env
      - Publisher/.env
    ports:
      - "80:8080"
    depends_on:
      - rabbitmq
  subscriber:
    image: devopsufscar/ps-subscriber
    restart: always
    container_name: subscriber
    env_file:
      - .env
      - ./Subscriber/.env
    depends_on:
      - publisher
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq