services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
  publisher:
    image: ps/publisher
    restart: always
    container_name: publisher
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
  subscriber:
    image: ps/subscriber
    restart: always
    container_name: subscriber
    env_file:
      - .env
      - ./subscriber/.env
    depends_on:
      - publisher
