#!/bin/bash

load_image() {
    
    echo "$(echo "Loading")" "$(echo $1)"

    minikube image load $1

    echo "$(echo "Loaded")" "$(echo $1)"
}

build_publisher_image() {
    
    ################################################
    # Gerando a imagem docker do publisher
    ################################################
    
    cd Publisher

    # eval ${minikube docker-env}

    mvn package clean
        
    load_image devopsufscar/ps-publisher

    cd ..
}

build_subscriber_image() {
    
    ################################################
    # Gerando a imagem docker do subscriber
    ################################################
    
    cd Subscriber
    
    # eval ${minikube docker-env}

    mvn package clean

    load_image devopsufscar/ps-subscriber

    cd ..
}

init_minikube() {

    ################################################
    # Inicializando o Minikube
    ################################################

    minikube start

    ################################################
    # Habilitando o Ingress
    ################################################

    minikube image load k8s.gcr.io/ingress-nginx/controller:v1.9.4

    minikube addons enable ingress

    ################################################
    # Inicializando o DashBoard
    ################################################

    minikube addons enable dashboard

    minikube addons enable metrics-server

    minikube dashboard &
}

################################################
# Verificando flag -ips
################################################

while getopts ":ips" option; do
   case $option in
      i) # inicialização minikube
         init_minikube
         load_image rabbitmq:3-management
         ;;
      p) # imagem ps-publisher
         build_publisher_image
         ;;
      s) # imagem ps-subscriber
         build_subscriber_image
         ;;
   esac
done

################################################
# Instalando via helm
################################################

helm install ps ps-chart