#!/bin/bash

################################################
# Removendo a configuração do Ingress
################################################

cd K8s

kubectl delete -f ingress.yaml

cd ..

################################################
# Removendo a configuração do subscriber
################################################

cd K8s/subscriber

kubectl delete -f deployment.yaml; kubectl delete -f secret.yaml;

cd ../..

################################################
# Removendo a configuração do publisher
################################################

cd K8s/publisher

kubectl delete -f deployment.yaml; kubectl delete -f service.yaml;  

kubectl delete -f configmap.yaml;

cd ../..

################################################
# Removendo a configuração do K8s (RabbitMQ)
################################################

cd K8s/rabbitmq

kubectl delete -f deployment.yaml; kubectl delete -f service.yaml

cd ../..