#!/bin/bash

build_publisher_image() {
    
    ################################################
    # Gerando a imagem docker do publisher
    ################################################
    
    cd Publisher

    # eval ${minikube docker-env}

    mvn package clean
        
    # minikube image load apenas funciona no docker 24

    minikube image load ps/publisher

    cd ..
}

build_subscriber_image() {
    
    ################################################
    # Gerando a imagem docker do subscriber
    ################################################
    
    cd Subscriber
    
    # eval ${minikube docker-env}

    mvn package clean
        
    # minikube image load apenas funciona no docker 24

    minikube image load ps/subscriber

    cd ..
}

load_rabbitmq_image() {
    minikube image load rabbitmq:3-management
}

init_minikube() {

    ################################################
    # Inicializando o Minikube
    ################################################

    minikube start

    ################################################
    # Habilitando o Ingress
    ################################################

    minikube image load k8s.gcr.io/ingress-nginx/controller:v1.9.4

    minikube addons enable ingress

    ################################################
    # Inicializando o DashBoard
    ################################################

    minikube addons enable dashboard

    minikube addons enable metrics-server

    minikube dashboard &
}

################################################
# Verificando flag -ib
################################################

while getopts ":ib" option; do
   case $option in
      i) # initialize minikube
         init_minikube
         ;;
      b) # build images
         build_publisher_image
         build_subscriber_image
         load_rabbitmq_image
         ;;
   esac
done

################################################
# Configurando o K8s (RabbitMQ)
################################################

cd K8s/rabbitmq

kubectl apply -f deployment.yaml; kubectl apply -f service.yaml

cd ../..

################################################
# Configurando o publisher
################################################

cd K8s/publisher

kubectl apply -f configmap.yaml

kubectl apply -f deployment.yaml; kubectl apply -f service.yaml; 

cd ../..

################################################
# Configurando o subscriber
################################################

cd K8s/subscriber

kubectl apply -f secret.yaml; kubectl apply -f deployment.yaml 

cd ../..

################################################
# Configurando o Ingress
################################################

cd K8s

kubectl apply -f ingress.yaml