apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.livraria.name }}
  labels:
    app: {{ .Values.global.livraria.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.livraria.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.livraria.name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: TRANSACAO_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: transacao_url
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-db-configmap
                  key: database_livraria_url
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: username
            - name: MYSQL_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: password
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              memory: "2Gi"
              cpu: 2