kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}-db-configmap 
data:
  database_transacao_url: jdbc:mysql://{{ .Release.Name }}-db:3306/Transacao?createDatabaseIfNotExist=true
  database_livraria_url: jdbc:mysql://{{ .Release.Name }}-db:3306/Livraria?createDatabaseIfNotExist=true
  database_user: root