#!/bin/bash

################################################
# Removendo a configuração do frontend
################################################

kubectl delete -f ingress.yaml; kubectl delete -f service.yaml

kubectl delete -f secret.yaml; kubectl delete -f deployment.yaml