#!/bin/bash

load_image() {
    
    echo "$(echo "Loading")" "$(echo $1)"

    minikube image load $1

    echo "$(echo "Loaded")" "$(echo $1)"
}

build_image() {
    
    ################################################
    # Gerando a imagem docker
    ################################################
    
    # eval ${minikube docker-env}

    cd image

    docker build . -t devopsufscar/hello-secret-env

    load_image devopsufscar/hello-secret-env

    cd ..
}

init_minikube() {

    ################################################
    # Inicializando o Minikube
    ################################################

    minikube start

    ################################################
    # Habilitando o Ingress
    ################################################

    minikube addons enable ingress

    ################################################
    # Inicializando o DashBoard
    ################################################

    minikube addons enable dashboard

    minikube addons enable metrics-server

    minikube dashboard &
}

################################################
# Verificando flags -ib
################################################

while getopts ":ib" option; do
   case $option in
      i) # initialize/start minikube
         init_minikube
         ;;  
      b) # build image
         build_image
         ;;
   esac
done

################################################
# Configurando o K8s
################################################

kubectl apply -f secret.yaml; kubectl apply -f deployment.yaml

sleep 10

kubectl apply -f service.yaml; 

sleep 10

kubectl apply -f ingress.yaml
