apiVersion: v1
kind: Service
metadata:
  name: cidades-backend
  labels:
    run: cidades-backend
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: cidades-backend
