services:
  frontend:
    image: contatos/frontend
    restart: always
    ports:
      - "80:80"
    networks: 
      - frontend
    depends_on:
      backend:
        condition: service_started
  
  backend:
    image: contatos/backend
    restart: always
    networks:
      - backend
      - frontend
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_URL: jdbc:mysql://db:3306/Contatos?createDatabaseIfNotExist=true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    healthcheck: #para garantir que o db vai estar completamente up antes de rodar o app
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
  
networks: 
  frontend:
  backend:
volumes:
  mysql-data: