#!/bin/bash

build_backend_image() {
    
    ################################################
    # Gerando a imagem docker do backend
    ################################################
    
    cd backend
    
    # eval ${minikube docker-env}

    mvn package clean
        
    # minikube image load apenas funciona no docker 24
    
    minikube image load contatos/backend

    cd ..
}

build_frontend_image() {
    
    ################################################
    # Gerando a imagem docker do frontend
    ################################################
    
    cd frontend
    
    # eval ${minikube docker-env}
    
    docker build . -t contatos/frontend
    
    minikube image load contatos/frontend

    cd ..
}

load_mysql_image() {
    minikube image load mysql:5.7
}

init_minikube() {

    ################################################
    # Inicializando o Minikube
    ################################################

    minikube start

    ################################################
    # Habilitando o Ingress
    ################################################

    minikube image load k8s.gcr.io/ingress-nginx/controller:v1.9.4

    minikube addons enable ingress

    ################################################
    # Inicializando o DashBoard
    ################################################

    minikube addons enable dashboard

    minikube addons enable metrics-server

    minikube dashboard &
}

################################################
# Verificando flag -b
################################################

while getopts ":ib" option; do
   case $option in
      i) # init minikube
         init_minikube
         ;;
      b) # build images
         build_backend_image
         build_frontend_image
         load_mysql_image
         ;;
   esac
done

################################################
# Instalando via helm
################################################

helm install contatos contatos-chart