#!/bin/bash

load_image() {
    
    echo "$(echo "Loading")" "$(echo $1)"

    minikube image load $1

    echo "$(echo "Loaded")" "$(echo $1)"
}

build_backend_image() {
    
    ################################################
    # Gerando a imagem docker do backend
    ################################################
    
    cd backend
    
    # eval ${minikube docker-env}

    mvn package clean

    load_image devopsufscar/contatos-v1-backend

    cd ..
}

build_frontend_image() {
    
    ################################################
    # Gerando a imagem docker do frontend
    ################################################
    
    cd frontend
    
    # eval ${minikube docker-env}
    
    docker build . -t devopsufscar/contatos-v1-frontend
    
    load_image devopsufscar/contatos-v1-frontend

    cd ..
}

init_minikube() {

    ################################################
    # Inicializando o Minikube
    ################################################

    minikube start

    ################################################
    # Habilitando o Ingress
    ################################################

    minikube addons enable ingress

    ################################################
    # Inicializando o DashBoard
    ################################################

    minikube addons enable dashboard

    minikube addons enable metrics-server

    minikube dashboard &
}

################################################
# Verificando flags -ib
################################################

while getopts ":ibf" option; do
   case $option in
      i) # initialize/start minikube
         init_minikube
         load_image mysql:5.7
         ;;  
      b) # build backend image
         build_backend_image
         ;;
      f) # build frontend image
         build_frontend_image
         ;;
   esac
done

################################################
# Configurando o K8s (DB)
################################################

cd K8s/db

kubectl apply -f secret.yaml; kubectl create -f pv.yaml; kubectl create -f pvc.yaml;

kubectl apply -f deployment.yaml; kubectl apply -f service.yaml;  

cd ../..

################################################
# Configurando o backend
################################################

cd K8s/backend

kubectl wait --for=jsonpath='{.status.phase}'=Running $(kubectl get pods -o=name) --timeout=300s

kubectl apply -f configmap.yaml; kubectl apply -f deployment.yaml; kubectl apply -f service.yaml;

cd ../..

################################################
# Configurando o frontend
################################################

cd K8s/frontend

kubectl apply -f deployment.yaml; kubectl apply -f service.yaml;  

cd ../..

################################################
# Configurando o Ingress
################################################

cd K8s

kubectl apply -f ingress.yaml
