#!/bin/bash

build_livraria_image() {
    
    ################################################
    # Gerando a imagem docker do LivrariaMVC
    ################################################
    
    cd LivrariaMVC
    
    mvn package clean

    cd ..
}

build_transacao_image() {
    
    ################################################
    # Gerando a imagem docker do TransacaoAPI
    ################################################
    
    cd TransacaoAPI
    
    mvn package clean
        
    cd ..
}

################################################
# Verificando flag -lt
################################################

while getopts ":lt" option; do
   case $option in
      l) # imagem livraria-mvc
         build_livraria_image
         ;;
      t) # imagem transacao-api
         build_transacao_image
         ;;
   esac
done

################################################
# Executando o docker compose
################################################

docker compose up
