services:
   db:
    image: mysql:5.7
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck: # Para garantir que o db vai estar completamente up antes de subir os demais conteineres
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="root" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
      
   transacao:
    image: devopsufscar/transacao-api
    restart: always
    env_file:
      - .env
      - TransacaoAPI/.env
    depends_on:
      db:
        condition: service_healthy

   livrariamvc:
    image: devopsufscar/livraria-mvc
    restart: always
    ports:
      - "80:8080"
    env_file:
      - .env
      - LivrariaMVC/.env
    depends_on:
      db:
        condition: service_healthy
      transacao:
        condition: service_started
volumes:
  mysql-data:
