services:
   db:
    image: mysql
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck: #para garantir que o db vai estar completamente up antes de rodar o app
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
  
   transacao:
    image: livraria/transacao-api
    restart: always
    env_file:
      - .env
      - TransacaoAPI/.env
    depends_on:
      db:
        condition: service_healthy

   livrariamvc:
    image: livraria/livraria-mvc
    restart: always
    ports:
      - "80:8080"
    env_file:
      - .env
      - LivrariaMVC/.env
    depends_on:
      db:
        condition: service_healthy
      transacao:
        condition: service_started
volumes:
  mysql-data:
