#!/bin/bash

load_image() {
    
    echo "$(echo "Loading")" "$(echo $1)"

    minikube image load $1

    echo "$(echo "Loaded")" "$(echo $1)"
}

build_livraria_image() {
    
    ################################################
    # Gerando a imagem docker do LivrariaMVC
    ################################################
    
    cd LivrariaMVC
    
    # eval ${minikube docker-env}

    mvn package clean

    load_image devopsufscar/livraria-mvc
    
    cd ..
}

build_transacao_image() {
    
    ################################################
    # Gerando a imagem docker do TransacaoAPI
    ################################################
    
    cd TransacaoAPI

    # eval ${minikube docker-env}
    
    mvn package clean

    load_image devopsufscar/transacao-api

    cd ..
}

init_minikube() {

    ################################################
    # Inicializando o Minikube
    ################################################

    minikube start

    ################################################
    # Habilitando o Ingress
    ################################################

    minikube image load k8s.gcr.io/ingress-nginx/controller:v1.9.4

    minikube addons enable ingress

    ################################################
    # Inicializando o DashBoard
    ################################################

    minikube addons enable dashboard

    minikube addons enable metrics-server

    minikube dashboard &
}

################################################
# Verificando flag -ilt
################################################

while getopts ":ilt" option; do
   case $option in
      i) # inicializando minikube
         init_minikube
         load_image mysql:5.7
         ;;
      l) # imagem livraria-mvc
         build_livraria_image
         ;;
      t) # imagem transacao-api
         build_transacao_image
         ;;
   esac
done

################################################
# Instalando via helm
################################################

helm install livraria livraria-chart