#!/bin/bash

load_image() {
    
    echo "$(echo "Loading")" "$(echo $1)"

    minikube image load $1

    echo "$(echo "Loaded")" "$(echo $1)"
}

build_livraria_image() {
    
    ################################################
    # Gerando a imagem docker do LivrariaMVC
    ################################################
    
    cd LivrariaMVC
    
    # eval ${minikube docker-env}

    mvn package clean
        
    load_image devopsufscar/livraria-mvc
    
    cd ..
}

build_transacao_image() {
    
    ################################################
    # Gerando a imagem docker do TransacaoAPI
    ################################################
    
    cd TransacaoAPI
    
    # eval ${minikube docker-env}

    mvn package clean
    
    load_image devopsufscar/transacao-api

    cd ..
}

init_minikube() {

    ################################################
    # Inicializando o Minikube
    ################################################

    minikube start

    ################################################
    # Habilitando o Ingress
    ################################################

    minikube image load k8s.gcr.io/ingress-nginx/controller:v1.9.4

    minikube addons enable ingress

    ################################################
    # Inicializando o DashBoard
    ################################################

    minikube addons enable dashboard

    minikube addons enable metrics-server

    minikube dashboard &
}

################################################
# Verificando flag -ilt
################################################

while getopts ":ilt" option; do
   case $option in
      i) # inicializando minikube
         init_minikube
         load_image mysql:5.7
         ;;
      l) # imagem livraria-mvc
         build_livraria_image
         ;;
      t) # imagem transacao-api
         build_transacao_image
         ;;
   esac
done

################################################
# Configurando o K8s (DB)
################################################

cd K8s/db

kubectl apply -f secret.yaml; kubectl create -f pv.yaml; kubectl create -f pvc.yaml;

kubectl apply -f deployment.yaml; kubectl apply -f service.yaml; kubectl apply -f configmap.yaml; 

cd ../..

################################################
# Configurando o Livraria-MVC
################################################

cd K8s/livraria

kubectl wait --for=jsonpath='{.status.phase}'=Running $(kubectl get pods -o=name) --timeout=300s

kubectl create -f deployment.yaml; kubectl create -f service.yaml; kubectl create -f configmap.yaml; 

cd ../..

################################################
# Configurando o TransacaoAPI
################################################

cd K8s/transacao-api

kubectl create -f deployment.yaml; kubectl create -f service.yaml;  

cd ../..

################################################
# Configurando o Ingress
################################################

cd K8s

kubectl apply -f ingress.yaml
