apiVersion: v2
name: livraria
description: A Helm chart for Livraria application
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: "db"
    version: "0.1.0"
  - name: "livraria"
    version: "0.1.0"
  - name: "transacao-api"
    version: "0.1.0"
