apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-node
  name: hello-node
spec:
  type: LoadBalancer
  ports:
  - nodePort: 31123
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: hello-node

