apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.backend.name }}
  labels:
    app: {{ .Values.global.backend.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.backend.name }}
    spec:
      containers:
        - name: {{ .Values.global.backend.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: CORS
              value: "*"
            - name: MONGO_INITDB_HOST
              value: {{ .Release.Name }}-db
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: password
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"