apiVersion: apps/v1
kind: Deployment
metadata:
  name: contatos-frontend
  labels:
    app: contatos-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contatos-frontend
  template:
    metadata:
      labels:
        app: contatos-frontend
    spec:
      containers:
        - name: frontend
          image: devopsufscar/contatos-v3-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: contatos-backend-configmap
                  key: url
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
