#!/bin/bash

build_image() {
    
    ################################################
    # Gerando a imagem docker livros-mvc
    ################################################
    
    cd LivrariaMVC
    
    # eval ${minikube docker-env}

    mvn package clean

    cd ..
}

################################################
# Verificando flag -b
################################################

while getopts ":b" option; do
   case $option in
      b) # imagem livros-mvc
         build_image
   esac
done

################################################
# Executando o docker compose (UP)
################################################

docker compose up
