#!/bin/bash

load_image() {

    # minikube image load apenas funciona no docker 24
    
    echo "$(echo "Loading")" "$(echo $1)"

    minikube image load $1

    echo "$(echo "Loaded")" "$(echo $1)"

    # Acredito que funciona para qualquer versão do docker
    # docker image save -o image.tar $1
    # minikube image load image.tar
    # rm image.tar
}

build_image() {
    
    ################################################
    # Gerando a imagem docker do product-mvc
    ################################################
    
    cd LivrariaMVC
    
    # eval ${minikube docker-env}

    mvn package clean

    load_image devopsufscar/livros-mvc
    
    cd ..
}

init_minikube() {

    ################################################
    # Inicializando o Minikube
    ################################################

    minikube start --memory 5120 --cpus 4 --nodes 3

    ################################################
    # Habilitando o Ingress
    ################################################

    minikube addons enable ingress

    ################################################
    # Inicializando o DashBoard
    ################################################

    minikube addons enable dashboard

    minikube addons enable metrics-server

    minikube dashboard &

    load_image cassandra:5.0.4
}

################################################
# Verificando flag -ib
################################################

while getopts ":ib" option; do
   case $option in
      i) # init minikube
         init_minikube
         ;;
      b) # build images
         build_image
         ;;
   esac
done

################################################
# Instalando via helm
################################################

helm install livraria livraria-chart