#!/bin/bash

load_image() {
    
    echo "$(echo "Loading")" "$(echo $1)"

    minikube image load $1

    echo "$(echo "Loaded")" "$(echo $1)"
}

build_image() {
    
    ################################################
    # Gerando a imagem docker do livros-mvc
    ################################################
    
    cd LivrariaMVC
    
    # eval ${minikube docker-env}

    mvn package clean

    load_image devopsufscar/livros-mvc
    
    cd ..
}

init_minikube() {

    ################################################
    # Inicializando o Minikube
    ################################################

    minikube start --memory 5120 --cpus 4 --nodes 3

    ################################################
    # Habilitando o Ingress
    ################################################

    minikube addons enable ingress

    ################################################
    # Inicializando o DashBoard
    ################################################

    minikube addons enable dashboard

    minikube addons enable metrics-server

    minikube dashboard &

    load_image cassandra:4.1.3
}

################################################
# Verificando flag -ib
################################################

while getopts ":ib" option; do
   case $option in
      i) # inicializando minikube
         init_minikube
         ;;
      b) # imagem livros-mvc
         build_image
         ;;
   esac
done

################################################
# Instalando via helm
################################################

helm install livraria livraria-chart