apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  labels:
    run: {{ .Release.Name }}-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-db
