apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.transacao.name }}
  labels:
    run: {{ .Values.global.transacao.name }}
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: {{ .Values.global.transacao.name }}
