apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.name" . }}
  labels:
    run: {{ include "hello-world.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
    #  nodePort: 30000
      protocol: TCP
      name: http
  selector:
    app: {{ include "hello-world.name" . }}
