services:
  frontend:
    image: devopsufscar/contatos-v2-frontend
    restart: always
    ports:
      - "80:80"
    networks: 
      - frontend
    depends_on:
      - backend
  
  backend:
    image: devopsufscar/contatos-v2-backend
    restart: always
    networks:
      - backend
      - frontend
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.2
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
  
networks: 
  frontend:
  backend:
volumes:
  mongo-data: