#!/bin/bash

build_app_image() {
    
    ################################################
    # Gerando a imagem docker do app
    ################################################
    
    cd app
    
    docker build . -t devopsufscar/todolist-app
    
    cd ..
}

################################################
# Verificando flag -b
################################################

while getopts ":b" option; do
   case $option in
      b) # imagem todolist-app
         build_app_image
   esac
done

################################################
# Executando o docker compose (UP)
################################################

docker compose up
