#!/bin/bash

build_app_image() {
    
    ################################################
    # Gerando a imagem docker do app
    ################################################

    cd app
    
    # eval ${minikube docker-env}

    docker build . -t devopsufscar/todolist-app

    # minikube image load apenas funciona no docker 24
    
    minikube image load devopsufscar/todolist-app

    cd ..
}

load_mongo_image() {
    minikube image load mongo:4.2
}

init_minikube() {

    ################################################
    # Inicializando o Minikube
    ################################################

    minikube start

    ################################################
    # Habilitando o Ingress
    ################################################

    minikube image load k8s.gcr.io/ingress-nginx/controller:v1.9.4

    minikube addons enable ingress

    ################################################
    # Inicializando o DashBoard
    ################################################

    minikube addons enable dashboard

    minikube addons enable metrics-server

    minikube dashboard &
}

################################################
# Verificando flag -ib
################################################

while getopts ":ib" option; do
   case $option in
      i) # init minikube
         init_minikube
         ;;
      b) # build images
         build_app_image
         load_mongo_image
         ;;
   esac
done

################################################
# Instalando via helm
################################################

helm install todolist todolist-chart