#!/bin/bash

build_app_image() {
    
    ################################################
    # Gerando a imagem docker do app
    ################################################
    
    cd app
    
    # eval ${minikube docker-env}

    docker build . -t devopsufscar/todolist-app

    # minikube image load apenas funciona no docker 24
    
    minikube image load devopsufscar/todolist-app

    cd ..
}

load_mongo_image() {
    minikube image load mongo:4.2
}

init_minikube() {

    ################################################
    # Inicializando o Minikube
    ################################################

    minikube start

    ################################################
    # Habilitando o Ingress
    ################################################

    minikube image load k8s.gcr.io/ingress-nginx/controller:v1.9.4

    minikube addons enable ingress

    ################################################
    # Inicializando o DashBoard
    ################################################

    minikube addons enable dashboard

    minikube addons enable metrics-server

    minikube dashboard &
}

################################################
# Verificando flag -ib
################################################

while getopts ":ib" option; do
   case $option in
      i) # initialize/start minikube
         init_minikube
         ;;
      b) # build images
         build_app_image
         load_mongo_image
         ;;
   esac
done

################################################
# Configurando o K8s (DB)
################################################

cd K8s/db

kubectl apply -f secret.yaml; kubectl create -f pv.yaml; kubectl create -f pvc.yaml;

kubectl apply -f deployment.yaml; kubectl apply -f service.yaml

cd ../..

################################################
# Configurando o app
################################################

cd K8s/app

kubectl wait --for=jsonpath='{.status.phase}'=Running $(kubectl get pods -o=name) --timeout=300s

kubectl apply -f deployment.yaml; kubectl apply -f service.yaml; 

cd ../..

################################################
# Configurando o Ingress
################################################

cd K8s

kubectl apply -f ingress.yaml