#!/bin/bash

################################################
# Removendo a configuração do Ingress
################################################

cd K8s

kubectl delete -f ingress.yaml

cd ..

################################################
# Removendo a configuração do app
################################################

cd K8s/app

kubectl delete -f deployment.yaml; kubectl delete -f service.yaml;  

cd ../..

################################################
# Removendo a configuração do K8s (DB)
################################################

cd K8s/db

kubectl delete -f deployment.yaml; kubectl delete -f service.yaml; kubectl delete -f configmap.yaml; kubectl delete -f secret.yaml;  

kubectl delete -f pvc.yaml; kubectl delete pv todolist-pv-volume

cd ../..