#!/bin/bash

################################################
# Desinstalando via Terraform
################################################

cd terraform

terraform destroy -auto-approve

rm -rf .terraform* terraform*


