#!/bin/bash

load_image() {
    
    echo "$(echo "Loading")" "$(echo $1)"

    minikube image load $1

    echo "$(echo "Loaded")" "$(echo $1)"
}

build_app_image() {
    
    ################################################
    # Gerando a imagem docker do app
    ################################################

    cd app
    
    # eval ${minikube docker-env}

    docker build . -t devopsufscar/todolist-app
    
    load_image devopsufscar/todolist-app

    cd ..
}

init_minikube() {

    ################################################
    # Inicializando o Minikube
    ################################################

    minikube start

    ################################################
    # Habilitando o Ingress
    ################################################

    minikube image load k8s.gcr.io/ingress-nginx/controller:v1.9.4

    minikube addons enable ingress

    ################################################
    # Inicializando o DashBoard
    ################################################

    minikube addons enable dashboard

    minikube addons enable metrics-server

    minikube dashboard &
}

################################################
# Verificando flag -ib
################################################

while getopts ":ib" option; do
   case $option in
      i) # inicializando minikube
         init_minikube
         load_image mongo:4.2
         ;;
      b) # imagem todolist-app
         build_app_image
         ;;
   esac
done

################################################
# Instalando via Terraform
################################################

cd terraform

terraform init

terraform apply -auto-approve
