#!/bin/bash

################################################
# Removendo a configuração do frontend
################################################

kubectl delete -f deployment.yaml; kubectl delete -f service.yaml