#!/bin/bash

build_backend_image() {
    
    ################################################
    # Gerando a imagem docker do backend
    ################################################
    
    cd backend

    docker build . -t devopsufscar/cidades-v1-backend
    
    cd ..
}

build_frontend_image() {
    
    ################################################
    # Gerando a imagem docker do frontend
    ################################################
    
    cd frontend
    
    docker build . -t devopsufscar/cidades-v1-frontend
    
    cd ..
}

################################################
# Verificando flags -bf
################################################

while getopts ":bf" option; do
   case $option in
      b) # imagem do backend
         build_backend_image
         ;;
      f) # imagem do frontend
         build_frontend_image
         ;;
   esac
done

################################################
# Executando o docker compose (UP)
################################################

docker compose up
