services:

  frontend:
    image: devopsufscar/cidades-v1-frontend
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
    
  backend:
    image: devopsufscar/cidades-v1-backend
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_URL: jdbc:mysql://db:3306/Cidades?createDatabaseIfNotExist=true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck: # Para garantir que o db vai estar completamente up antes de subir os demais conteineres
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="root" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    
volumes:
  mysql-data: