apiVersion: v1
kind: Service
metadata:
  name: transacao-api
  labels:
    run: transacao-api
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: transacao-api
