#!/bin/bash

################################################
# Inicializando o Minikube
################################################

minikube start --cpus 4 --memory 4096

################################################
# Habilitando o Ingress
################################################

minikube image load k8s.gcr.io/ingress-nginx/controller:v1.9.4

minikube addons enable ingress

################################################
# Inicializando o DashBoard
################################################

minikube addons enable dashboard

minikube addons enable metrics-server

minikube dashboard &

################################################
# Configurando o K8s
################################################

kubectl apply -f deployment.yaml; kubectl apply -f service.yaml 

################################################
# Configurando o Ingress
################################################

kubectl wait --for=jsonpath='{.status.phase}'=Running $(kubectl get pods -o=name)

kubectl apply -f ingress.yaml