apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.subscriber.name }}-secret
type: kubernetes.io/basic-auth
data:
  username: ZGVsYW5vYmVkZXJAZ21haWwuY29tCg==
  password: cWlyeWNzcGhjZ29xb3Zycgo=