apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.rabbitmq.name }}
  labels:
    run: {{ .Values.global.rabbitmq.name }}
spec:
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
  selector:
    app: {{ .Values.global.rabbitmq.name }}
