services:
   db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
  
   transacao:
    image: livraria/transacao-api
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_URL: jdbc:mysql://db:3306/Transacao?createDatabaseIfNotExist=true
    depends_on:
      - db

   livrariamvc:
    image: livraria/livraria-mvc
    ports:
      - "80:8080"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_URL: jdbc:mysql://db:3306/Livraria?createDatabaseIfNotExist=true
      TRANSACAO_API_URL: http://transacao:8081
    depends_on:
      - db
      - transacao 
volumes:
  mysql-data:
