services:
   db:
    image: mysql
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
  
   transacao:
    image: livraria/transacao-api
    restart: always
    env_file:
      - .env
      - TransacaoAPI/.env
    depends_on:
      - db

   livrariamvc:
    image: livraria/livraria-mvc
    restart: always
    ports:
      - "80:8080"
    env_file:
      - .env
      - LivrariaMVC/.env
    depends_on:
      - db
      - transacao 
volumes:
  mysql-data:
