apiVersion: v1
kind: Service
metadata:
  name: todolist
  labels:
    run: todolist
spec:
  #type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: todolist
